### ISSUE TITLE
tooling: Set up Travis on the new repo

### ISSUE THREAD

**Issue by showell** [zulip/python-zulip-api#10]
We need to figure out ways to run these kinds of things on our newly split out repo

* ./tools/lint (from server repo, should run on api repo and borrow code somehow)
* bots automated tests (should run on new repo ideally)
* api tests (these should actually stay on the server repo for the short term, but we could move them here if we had a way to set up a test server)

This ticket is not for beginners.

**Comment by timabbott** [comment]
We have Travis running with both lint and the bot tests, so closing this; I think it might be reasonable to open an issue for new forms of coverage that we want to add...
