### ISSUE TITLE
Pass both raw content and stripped content to bots

### ISSUE THREAD

**Issue by timabbott** [zulip/python-zulip-api#138]
Some bots will want access to the entire message, others to just content after the mention.  We should respect this by just providing both the raw content of the message as well as the content after the mention, probably as `content` and `content_after_mention`.  That way, bots can interact with either or both according to what makes sense for the bot.  

(As a sidenote, we probably want `content_after_mention` to be all content after the first mention, with no requirement for the mention to be at the start of the message)

**Comment by timabbott** [comment]
This is based on feedback on chat.zulip.org, but @showell and @derAnfaenger FYI in case you have thoughts on this.

**Comment by showell** [comment]
Seems kinda ugly, but I guess I understand the concern, as parsing it away is annoying, and I see why some folks will want the whole message.

**Comment by timabbott** [comment]
I think it's not that ugly, because we're just passing a dict to the bots, so it's just an extra key there available for them to interact with.
