### ISSUE TITLE
Improve third-party config file scheme for external bots.

### ISSUE THREAD

**Issue by showell** [zulip/python-zulip-api#162]
We should not have bot_lib ever read third-party configuration data out of source-controlled files.  We should instead require users to make their own config files that they can put somewhere outside the source tree, most likely in their home directory.

What we can do is provide a template file for the users, like giphy.conf.template.

**Comment by roberthoenig** [comment]
@showell can this be closed with https://github.com/zulip/python-zulip-api/commit/536ba1843a9faf2ff139f06b917f67d3ee8edd3f?

**Comment by showell** [comment]
oh, yep, absolutely

There is some follow-up work to do here, but it will come up organically.

Closing.
