### ISSUE TITLE
followup: Provide help text as a reply.

### ISSUE THREAD

**Issue by aero31aero** [zulip/python-zulip-api#173]
Unlike most other bots, followup bot doesn't supply a help text on running `@botname help`.

On sending `help`, we should respond only with the help text of the bot stop the control flow there.

**Comment by aero31aero** [comment]
@zulipbot label "bite size"

**Comment by nkmishra1997** [comment]
@zulipbot claim

**Comment by nkmishra1997** [comment]
The current Help Text is

> This plugin will allow users to flag messages as being follow-up items.  Users should preface messages with "@mention-bot". Before running this, make sure to create a stream called "followup" that your API user can send to.

I think we can update this as well once the #200 is merged:

> Before running this, make sure to create a stream called "followup" that your API user can send to OR you can specify a custom stream in the stream_detail.config file.

**Comment by aero31aero** [comment]
Sounds good to me. :)
