### ISSUE TITLE
Fully move zulip_bots to Python 3.

### ISSUE THREAD

**Issue by roberthoenig** [zulip/python-zulip-api#187]
We have dumped Python 2 support for the zulip_bots and zulip_botserver packages. I am opening this issue to track progress on converting remaining code shreds from Python 2 legacy support to Python 3 only.

- [x] - move all shebangs from `#!/usr/bin/env python` to `#!/usr/bin/env python3`
- [ ] - move remaining six imports
- [ ] - remove any python 2-related checks.

Feel free to comment additional steps to be taken here.

**Comment by roberthoenig** [comment]
@fredfishgames assigning you for the first checkbox :) When you submit your PR, mention this issue in the PR description.

**Comment by sibasish14** [comment]
@roberthoenig can I work on this issue for the first check?
I have to change the `python` to `python3` in all shebangs of `zulip_bots` and `zulip_botserver` packages right?

**Comment by fredfishgames** [comment]
@sibasish14 We decided to do this for `zulip_bots`, but not the test scripts. @showell did it in [this commit](https://github.com/zulip/python-zulip-api/commit/fd069dff82b98785ea23183f7f5313c782351474).

**Comment by sibasish14** [comment]
Ok @fredfishgames
Can you suggest any other issue though? I'm a beginner by the way.
Or should I look for a beginner issue in the main zulip repo?

**Comment by showell** [comment]
We can actually change the test scripts that pertain to zulip_bots.

(My earlier comments were probably me just being cautious until we were sure, but I'm confident now that we want to make the move.)

**Comment by sibasish14** [comment]
@showell  you want `python3` shebangs to be introduced in the `zulip_bot` test scripts? So can I do that?

**Comment by sibasish14** [comment]
@showell waiting for your reply :)
If you could please tell me if you wanted to proceed ahead, I could start working. Else I'll look for some other issue :(

**Comment by neiljp** [comment]
@sibasish14: @showell may well be away for the holidays right now, so you might want to wait a few days at least - is there something else you can work on?

**Comment by sibasish14** [comment]
@neiljp : may be I'll move on to some other issue for now. But I'll start working on this one once @showell gives me the green signal ;)

**Comment by showell** [comment]
yes, python3 shebangs for the zulip_bot test scripts would be good

**Comment by sibasish14** [comment]
@showell I'll get to work.

**Comment by sibasish14** [comment]
Can someone please have a look at https://github.com/zulip/python-zulip-api/pull/259 ?

**Comment by showell** [comment]
The PR #277 will close this once it's merged.  We may have additional steps to kill off py2 for bots in the future, but this ticket is starting to create confusion, since most of the tasks have been already completed.  Folks should feel free to open more specific tickets about python2 pitfalls as they come up.
