### ISSUE TITLE
Improve Tests for Baremetrics Bot.

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [zulip/python-zulip-api#272]
The current tests do not accurately simulate the real world scenarios for the bot. It would be great if we use the test responses supplied on the baremetrics API documentation as fixtures. These contain actual data for "list-plans", etc., so these tests would verify that the bot works correctly with "real" data. 

This was on suggestion of @roberthoenig

**Comment by ViRu-ThE-ViRuS** [comment]
@zulipbot claim

**Comment by showell** [comment]
Closing this via #273
