### ISSUE TITLE
Set User-Agent correctly for Zulip bots

### ISSUE THREAD

**Issue by timabbott** [zulip/python-zulip-api#28]
We should set User-Agent so it is easy for the Zulip server's logging to track usage of the various bots.

The pattern we've established for this sort of thing is e.g. `ZulipTrelloWebhook` for our webhooks.  So I think we probably want e.g. `ZulipConverterBot` as the naming scheme for these.  Ideally, the framework would generate the client name, so there's no need to make any individual per-bot changes.  

We would pass this as an extra option to `zulip.Client` or `zulip.init_from_options` (depending what we're using).

**Comment by neiljp** [comment]
Working on this just now.

**Comment by neiljp** [comment]
How does #33 look as a resolution to this?
