### ISSUE TITLE
zulip 0.4.0 lists runtime dependency on `mock`

### ISSUE THREAD

**Issue by glyph** [zulip/python-zulip-api#293]
0.3.9 didn't; this should probably not be required except for testing.

**Comment by roberthoenig** [comment]
Thanks for the report @glyph! @eeshangarg FYI. This change came along with my recent commits to the packaging. `mock` should be only a dependency for the developer install.

**Comment by eeshangarg** [comment]
@glyph: Thanks for reporting this! Fixed in #294 :)
