### ISSUE TITLE
Port merels to game_handler

### ISSUE THREAD

**Issue by fishfred** [zulip/python-zulip-api#305]
(advanced) `merels` needs to be ported to game_handler, which is the new library used for games so that they can be made easily. It is not like any of the other games (tictactoe and connect four), so game_handler will probably have to be modified for it to work. Feel free to message me in #integrations if you have any questions about game_handler.

**Comment by amanagr** [comment]
@zulipbot claim

**Comment by amanagr** [comment]
@zulipbot abandon
