### ISSUE TITLE
Weather bot: Appears to fail existing tests when run with python3 

### ISSUE THREAD

**Issue by neiljp** [zulip/python-zulip-api#31]
With the code from #27 I see this detail of the failure using `python3 -m unittest discover`:

```
AssertionError: Calls to send_reply do not match those expected
MESSAGE:
{'content': 'New York'}
ACTUAL CALLS:
[call({'content': 'New York'}, 'Weather in New York, US:\n71.32999999999998 F / 21.850000000000023 C\nMist')]
EXPECTED:
[call({'content': 'New York'}, 'Weather in New York, US:\n71.33 F / 21.85 C\nMist')]
```

The test passes with python2 (2.7.13), whereas python3 here is 3.5.3 currently.

I'm guessing this is some kind of rounding error, and will look into it.

**Comment by neiljp** [comment]
This should be fixed, now that #32 is merged.

**Comment by neiljp** [comment]
While #32 was seemingly a good fix, it now seems to fail for another part of the weather test:
```
MESSAGE:
{'content': 'United Kingdom'}
ACTUAL CALLS:
[call({'content': 'United Kingdom'}, 'Weather in London, GB:\n58.73 F / 14.85 C\nShower Rain')]
EXPECTED:
[call({'content': 'United Kingdom'}, 'Weather in London, GB:\n58.33 F / 14.85 C\nShower Rain')]
```

**Comment by timabbott** [comment]
The actual numbers are different there.  Does this test have mocks for the network requests?  If not, it's probably just the actual temperature having changed?

**Comment by neiljp** [comment]
There are mocks in there; the test harness has:
```
        bot_response = "Weather in London, GB:\n58.33 F / 14.85 C\nShower Rain"
        with self.mock_config_info({'key': '123456'}), \
                self.mock_http_conversation('test_only_country'):
            self.initialize_bot()
            self.assert_bot_response(
                message = {'content': 'United Kingdom'},
                response = {'content': bot_response},
                expected_method='send_reply'
            )
```

I think the key thing here is that the **C** result is identical but the **F** result is not, which suggests to me a calculation error. The scaling is only a factor of ~2 (9/5), so we could expect the 0.4F difference to have a ~0.2C change, which would be noticeable.

**Comment by neiljp** [comment]
Online research suggests 58.73F is correct. This leads me to suggest that the original test was not taking into account python2 integer division. Hence #37.
