### ISSUE TITLE
Make game handler bots take shorthand moves.  (e.g. connect four)

### ISSUE THREAD

**Issue by showell** [zulip/python-zulip-api#329]
It's kind of tedious to say "move 7" when you're playing connect four.  We should probably allow just "7" as the command, and the game handler can have an option to assume numbers correspond to moves.

**Comment by DhruvThakker** [comment]
@zulipbot claim

**Comment by DhruvThakker** [comment]
@zulipbot abandon

**Comment by showell** [comment]
I merged some changes for this, so closing.
