### ISSUE TITLE
Add "show rules" support to game_handler.py.

### ISSUE THREAD

**Issue by showell** [zulip/python-zulip-api#330]
For things like connect four, there should be a quick way to learn the rules of the game. We could probably make this mandatory for all games that use game_handler.py, since you can always link somewhere on the web for more complicated games.

Something simple is usually good--for connect four, just say "Try to get four pieces in a row.  Diagonals count, too!"

**Comment by Kumar-Tarun** [comment]
@showell I'm taking this issue.

**Comment by Shivamgera** [comment]
@Kumar-Tarun Are you still working on this issue? @showell I guess the task here is to define a function in ```game_handler.py``` to briefly show the rules of all the games that use ```game_handler.py``` like connect four, tictactoe, etc. Can I work on this if @Kumar-Tarun  is not working?

**Comment by Kumar-Tarun** [comment]
@Shivamgera Yep, I've submitted a PR of game of fifteen, which has one commit incorporating that change :)

**Comment by neiljp** [comment]
A relevant commit appears to be merged; please confirm this can now be closed? @Kumar-Tarun @showell
