### ISSUE TITLE
Automatically add a bot handler's parent dir to the python path

### ISSUE THREAD

**Issue by noemartinez** [zulip/python-zulip-api#356]
The existing ```zulip-run-bot``` support for running a python file directly (instead of an existing bot in zulip_bots by name) works pretty well:

``` bash
zulip-run-bot  <path_to_handler_py_file> --config-file <path_to_zuliprc>
```

The only small inconvenience is that by default the bot can't import sibling python packages in the same directory as the bot's handler file that is being run. Could we automatically add the handler's parent dir to python's path as part of the ```zulip-run-bot``` process so the bot automatically has access to modules and packages deployed alongside it?

See [this conversation](https://chat.zulip.org/#narrow/stream/127-integrations/subject/standalone.20bot.20code/near/547688) for more context on this issue.

**Comment by novokrest** [comment]
@timabbott I added another PR #382 to fix this issue. It is ready for review.
