### ISSUE TITLE
Add test coverage reporting to our codebase and Travis CI

### ISSUE THREAD

**Issue by timabbott** [zulip/python-zulip-api#38]
This will help a lot for working towards having a complete test suite in this project.

I think we can borrow most of the logic from `tools/test-backend` in the server repo.

**Comment by derAnfaenger** [comment]
Just to get this right, we basically want the two commands 
`python -m unittest discover -v zulip_botserver` and
`tools/test-bots`
to be executed by a `test-backend` script, that also tests for coverage with codecov?

**Comment by timabbott** [comment]
I'd probably call it `tools/test-all`?  But yeah, whatever we call it, we want to run the various test suites using the `python-coverage` API to collect coverage data.  It has support for merging data from a few suites (which we use in `test-backend` because we run things in parallel).

(I think it might also be reasonable to just make `test-bots` test the `zulip_botserver` package too, if those tests are fast anyway).
