### ISSUE TITLE
Fix spammy BeautifulSoup output in `tools/test-bots`

### ISSUE THREAD

**Issue by timabbott** [zulip/python-zulip-api#39]
We should figure out how to fix this warning.  

```
test_bot (zulip_bots.bots.encrypt.test_encrypt.TestEncryptBot) ... ok
test_bot (zulip_bots.bots.thesaurus.test_thesaurus.TestThesaurusBot) ... /srv/zulip-venv/local/lib/python2.7/site-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 82 of the file ./tools/test-bots. To get rid of this warning, change code that looks like this:

 BeautifulSoup(YOUR_MARKUP})

to this:

 BeautifulSoup(YOUR_MARKUP, "lxml")

  markup_type=markup_type))
ok
test_404 (zulip_bots.bots.github_detail.test_github_detail.TestGithubDetailBot) ... ok
```

What I don't get is where we're calling BeautifulSoup the wrong way, given this:

```
$ git grep Beautif
zulip_bots/zulip_bots/bots/youtube/youtube.py:from bs4 import BeautifulSoup
zulip_bots/zulip_bots/bots/youtube/youtube.py:            soup = BeautifulSoup(r.text, 'lxml')
```

I'd love to see this debugged, since we actually have a similar problem in the server project with some code using BeautifulSoup...

**Comment by derAnfaenger** [comment]
The problem seems to be the library `PyDictionary` used by the thesaurus bot.
According to [this](https://github.com/geekpradd/PyDictionary/issues/1) issue on PyDictionary's repo, it was a file `utils.py` that caused their code to throw this warning. The line numbers provided by BeautifulSoup are completely confusing and irrelevant in this case.

I checked out the PyDictionary repo, they updated their code recently so it does not throw a warning anymore. However, the `pip` package has not been updated yet, so I guess it's just a matter of time.

**Comment by timabbott** [comment]
We could move our `requirements.txt` to using a version of PyDictionary from Git to resolve this before their release.  See zulip.git/requirements/* for a bunch of examples of doing this (though don't use `-e`).

**Comment by derAnfaenger** [comment]
@timabbott tried to apply your approach - I wasn't able to install `PyDictionary` directly via `git+git://github.com/geekpradd/PyDictionary.git`, since there strangely is no `setup.py` in their main repo.

**Comment by timabbott** [comment]
Well, that's annoying.  I pinged the issue in PyDictionary's repo, in the hopes of getting upstream to deal.

**Comment by derAnfaenger** [comment]
Closing this, since #75 removed the Thesaurus bot and thus the PyDictionary dependency.
