### ISSUE TITLE
Fix bugs on Python 3 and add to Travis builds

### ISSUE THREAD

**Issue by gnprice** [zulip/python-zulip-api#44]
Currently we have only Python 2.7 in the .travis.yml in this repo, leaving us open to regressions in our Python 3 support. We should add `3.4` to the list of Python versions, like we have in the Zulip server repo, and fix the bugs that show up when we do that.

At a [quick test](https://travis-ci.org/gnprice/python-zulip-api/jobs/259568217) on my own fork of the repo, there look to be at least a couple of Python 3-related bugs we can fix.

**Comment by timabbott** [comment]
Might be worth testing 3.5 and 3.6 as well.

**Comment by gnprice** [comment]
Yeah, agreed -- that's something we're going to want to pursue in the server too ASAP, I think.

On that side it'd be a burden to run all the tests on all those versions every commit, but we can figure something out. On this side, the Travis build as a whole is pretty fast, and also because it's a library there's a fair amount of value in supporting a range of versions, so we should probably run on the full set of 2.7, 3.4, 3.5, and 3.6. (I did a quick web search for stats on which old 3.x versions are still in use -- [this](https://semaphoreci.com/blog/2016/11/11/python-versions-used-in-commercial-projects-2016-edition.html) from late last year suggests 3.4 should make the cut and 3.3 shouldn't.)
