### ISSUE TITLE
Write a nice wrapper for `GET /messages` that will loop and download a user or stream's history

### ISSUE THREAD

**Issue by timabbott** [zulip/python-zulip-api#476]
Now that we have documented the `get_messages` API, it'd be really good to write a simple sample tool that correctly implements Zulip's looped-pagination logic for fetching the entire history of a narrow and storing it locally in a JSON file.  We can advertise that as a simple data export tool using the API, and it also would serve as a nice demonstration of how to use the `anchor` logic correctly.

**Comment by JayjeetAtGithub** [comment]
Looks interesting ! @timabbott can u pls elaborate and tell me where to begin ?

**Comment by JayjeetAtGithub** [comment]
Hi , @timabbott can u give me some idea how to approach the issue
