### ISSUE TITLE
bridge_with_irc: Check if the bot is subscribed to the relevant stream on startup.

### ISSUE THREAD

**Issue by rht** [zulip/python-zulip-api#500]
This way, the important precaution to make sure that the bot is subscribed is no longer necessary, since the bot will print out the problem itself.

**Comment by orientor** [comment]
@rht I saw your PR after making my PR. Our approaches are different though. I am checking it before initializing the bot. Also I have fully tested my PR. Kindly review.

**Comment by rht** [comment]
Regardless of where the check happens, IMO my solution is more concise. I did in 3 lines of what you did for checking the subscription. Sorry if I am biased, we need a 3rd party to break the tie. If @neiljp can take a look?

**Comment by orientor** [comment]
@rht yes you're right. BTW I tested your code and it works properly. So it can be merged.
