### ISSUE TITLE
bots: Do not pass all messages to bot in a group PM.

### ISSUE THREAD

**Issue by aero31aero** [zulip/python-zulip-api#551]
If a bot is part of a group PM, the conversation can easily get out of hand.

![image](https://user-images.githubusercontent.com/8033238/76867515-9fdc9e00-688b-11ea-8965-a4df63687532.png)

Instead, we should apply the same rules as stream messages for PMs with more than 2 recipients (mandatory @-mention before the bot's name).

**Comment by TAM360** [comment]
@aero31aero does this have an open PR too?

**Comment by xeruf** [comment]
is there a straightforward way for a bot to opt out of this behavior and handle all messages received in a group?

**Comment by timabbott** [comment]
No but we'd definitely accept a PR to add an option to do it. Might be worth discussing naming in #integrations on chat.zulip.org before implementing, but it's not hard to find/replace.
