### ISSUE TITLE
bots: Do not remove self from the list of recipients of the incoming message.

### ISSUE THREAD

**Issue by aero31aero** [zulip/python-zulip-api#552]
The current behavior of `send_reply` can be traced back to ad25f278534bc21310c1e3bd8a8021154bc19126.

(This change is part of the larger changes including some in the server repo to improve the UX for using bots in group PMs.)

**Comment by TAM360** [comment]
Hey @aero31aero, can I work on this issue?

**Comment by aero31aero** [comment]
Hey @TAM360 there's already an open PR fixing this issue. If you want a bots related issue and can't find one, you can start a discussion in #integrations stream on chat.zulip.org and we can find you a project. 😃

**Comment by TAM360** [comment]
Best!
