### ISSUE TITLE
twitter bot: Links not showing up in echoed tweets?

### ISSUE THREAD

**Issue by rishig** [zulip/python-zulip-api#57]
This tweet: https://twitter.com/zulip/status/895473932278431744
![image](https://user-images.githubusercontent.com/890911/29224175-133373f6-7e7e-11e7-9d2d-c5d50b0f53ef.png)

shows up as the following on https://chat.zulip.org/#narrow/stream/twitter/subject/zulip/near/265158
![image](https://user-images.githubusercontent.com/890911/29224117-c8fdf22a-7e7d-11e7-98ac-933cd191f73c.png)

Namely, the chat.zulip.org version doesn't have the docs.google.com link. 
I'm also not sure why it has the https://twitter.com/i/web/status/895473932278431744 link .. is that the link to the attached image?

**Comment by timabbott** [comment]
@HarshitOnGitHub is this something you can look into?  Now that I understand the issue a bit better, it's clearly going to be on the Bugdown side of things.

**Comment by HarshitOnGitHub** [comment]
@timabbott This one seems to be interesting! Looking into it. Retweets of the mentioned tweet are rendering properly: 
https://chat.zulip.org/#narrow/stream/test.20here/subject/long.20links/near/265858
https://chat.zulip.org/#narrow/stream/test.20here/subject/long.20links/near/265859

**Comment by HarshitOnGitHub** [comment]
I digged into this a little bit and results are a bit perplexing. I fetched the tweet data for the mentioned tweet and a retweet for checking out what's going. The `urls` key in the fetched data had different urls for tweet and retweet. Further the rendered tweet seemed to be in accordance to what was given to the bugdown processor so to me this seems to be a quirk on twitter's side. I think we can safely close this @timabbott.
For reference here is the `urls` key from data for the two tweets:
Original tweet:
```
    "urls": [
      {
        "url": "https:\/\/t.co\/k4uBodrNwg",
        "expanded_url": "https:\/\/twitter.com\/i\/web\/status\/895473932278431744",
        "display_url": "twitter.com\/i\/web\/status\/8\u2026",
        "indices": [
          105,
          128
        ]
      }
    ]
```
A random retweet:
```
      "urls": [
        {
          "url": "https:\/\/t.co\/EEFwXCwGEX",
          "expanded_url": "https:\/\/docs.google.com\/forms\/d\/e\/1FAIpQLSd-atYzq0o4cygxtntXgYHt21Cjte2xGjxXlMcLuBUuhybNXg\/viewform?usp=sf_link",
          "display_url": "docs.google.com\/forms\/d\/e\/1FAI\u2026",
          "indices": [
            115,
            138
          ]
        }
      ]
```

**Comment by timabbott** [comment]
Hmm, OK, yeah, sounds like a bug on Twitter's end.  Thanks for investigating!
