### ISSUE TITLE
get subscription status 

### ISSUE THREAD

**Issue by tdupu** [zulip/python-zulip-api#610]
The get subscription status doesn’t work “out of the box”. 

I messed with the URL and this didn’t work.
It might be the case that you need to compile from from source or be running from some sort of dev install. 

Fix: a simple function should be written for this
    https://zulipchat.com/api/get-subscription-status

**Comment by timabbott** [comment]
@akashaviator can you add a function for this?

**Comment by akashaviator** [comment]
@timabbott We can close this issue as it was fixed by 624cef01.

**Comment by timabbott** [comment]
OK, great :)
