### ISSUE TITLE
Migrate from travis-ci.org to travis-ci.com

### ISSUE THREAD

**Issue by rht** [zulip/python-zulip-api#626]
Travis-CI.org will be shut down on December 31, 2020: https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom?e=%5BUNIQID%5D

Migration instructions here: https://docs.travis-ci.com/user/migrate/open-source-repository-migration

Also remember to update the Travis badge in the README.md.

Make sure to read the discussion at: https://chat.zulip.org/#narrow/stream/2-general/topic/Travis-CI.2Eorg.20shuts.20down.20on.20December.2031.2C.202020

**Comment by alexmv** [comment]
Mooted by moving to Github Actions.
