### ISSUE TITLE
Opening search results in a popup dialog - Giphy Bot

### ISSUE THREAD

**Issue by grigala** [zulip/python-zulip-api#658]
This is more of a question than an issue. 

I'm wondering if there's anything already in the API that I can leverage with to implement this kind of behavior?

Basically all I want the bot to do instead of sending random picked GIF results, is to collect search results and show them in a popup window while the user types the search keyword. 

Not sure if you are familiar with Telegram's GIF bot, but that's the behavior I want to replicate in a nutshell.

**Comment by amanagr** [comment]
There is some progress in https://github.com/zulip/zulip/pull/17068 regarding this. I expect it to be in a good state by the end of March.

**Comment by grigala** [comment]
@amanagr oh cool! Asking this was a good idea then 😁 Thanks. Will close this one.
