### ISSUE TITLE
issue with mute_topic endpoint

### ISSUE THREAD

**Issue by mkp6781** [zulip/python-zulip-api#677]
I made a call to the endpoint with a non-existent topic and it returned a 'success' response.
Further if I make calls with this same topic, depending on whether the operation specified is add/remove I get the following responses.
"add" : `{'result': 'error', 'msg': 'Topic already muted'}`
"remove" : `{'result': 'error', 'msg': 'Topic is not muted'}`

**Comment by alexzw7** [comment]
@zulipbot add "good first issue"

**Comment by alexzw7** [comment]
@zulipbot claim

**Comment by timabbott** [comment]
@mkp6781 can you explain in more detail what you were trying to do?

I don't think this is a bug -- in Zulip, there is no concept of a "non-existent topic" -- topics are just a field on Message objects.  And muting adjusts the behavior of messages with that string in their topic field.
