### ISSUE TITLE
Rename BotHandler to AbstractBotHandler.

### ISSUE THREAD

**Issue by rht** [zulip/python-zulip-api#690]
To prevent confusion about its usage. To cement the fact that it is an abstract class used only for typing annotation purpose.
See discussion at https://chat.zulip.org/#narrow/stream/127-integrations/topic/deploying.20bots.20on.20heroku.3F.3F.3F.20--.20BotHandler.

Still need discussion: whether we should additionally use `NotImplementedError` instead of `...` to proactively tell the library users if they accidentally use the class.

**Comment by timabbott** [comment]
I think a naming change is likely sufficient to avoid library users accidentally using this class; we can always do something further after if we see the same confusion after a rename.
