### ISSUE TITLE
bot server: Add supervisord configuration

### ISSUE THREAD

**Issue by showell** [zulip/python-zulip-api#7]
see https://github.com/zulip/zulip/issues/5359

from vabs22:

Add supervisord configuration for running the server persistently and simplifying the server setup.
e.g. install-zulip-flask-supervisord <path_to_flaskbotrc>

**Comment by derAnfaenger** [comment]
Would it be enough to simply add a section in our documentation for supervisord that provides a config chunk users can paste in their `supervisord.conf`?

**Comment by timabbott** [comment]
I think that'd be a reasonable place to start, yeah.
