### ISSUE TITLE
zulip 0.8.1 release on PyPI is missing py.typed

### ISSUE THREAD

**Issue by caizixian** [zulip/python-zulip-api#732]
There is `py.typed` in https://files.pythonhosted.org/packages/7b/e8/8655a8d7f6d62b5781418bf2da81b9eed6bb519af6da12fee3b78ed1e513/zulip-0.8.0-py3-none-any.whl
But not in https://files.pythonhosted.org/packages/1b/da/cd4d2fac58b7211fcf875a4f9f78297b6d38caccda9fe506432961381fdf/zulip-0.8.1-py3-none-any.whl

I think this causes `mypy` checks of projects that imports `zulip` to fail.
```
error: Skipping analyzing "zulip": found module but no type hints or library stubs
note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```

**Comment by timabbott** [comment]
@eeshangarg can you investigate?  @PIG208 might also have ideas.

**Comment by caizixian** [comment]
@eeshangarg I'm wondering whether a new version, e.g. 0.8.2, can be released to PyPI to address this issue. Thanks!
