### ISSUE TITLE
Invalid email for valid email

### ISSUE THREAD

**Issue by Anton-4** [zulip/python-zulip-api#764]
I'm getting an invalid email error for a valid email address :shrug:
I checked the source code but I was unable to find where the email validation is happening.

![zulip-send-error](https://user-images.githubusercontent.com/17049058/186463036-ff788480-d2df-4496-805d-846fc212d089.png)

context: I'm trying to send a private message to the zulip user(me) with the email in the picture, shown as coming from a (generic) bot I just created.

**Comment by andersk** [comment]
Does your organization have [restricted email address visibility](https://zulip.com/help/restrict-visibility-of-email-addresses) turned on? If so, you need to use your display email address `userNNNN@roc.zulipchat.com` (where `NNNN` is your user ID) rather than your real email address.

**Comment by Anton-4** [comment]
Yes indeed, thank you @andersk!
