### ISSUE TITLE
default argument to Client.call_on_each_event's event_type param should be an empty list, or set to one

### ISSUE THREAD

**Issue by alphor** [zulip/python-zulip-api#86]
Example:
``` python3
    c = zulip.Client(
        email="user@example.com",
        site="https://zulip.com/api",
        api_key="key")
    c.call_on_each_event(
        lambda msg: print(str(msg) + "\n"))
```

returns:
```
Server returned error:
event_types is not a list
```

The current argument for [call_on_each_event](https://github.com/zulip/python-zulip-api/blob/095cea7ab9518dfd9658b03df69ab876bb6e1268/zulip/zulip/__init__.py#L499)'s event_types is defined as None, but it's never set to a list within the function body. Passing an empty list for event_types works as expected.

**Comment by timabbott** [comment]
@alphor thanks for the bug report!  I agree with your diagosis.  Want to submit a quick PR fixing this?

**Comment by alphor** [comment]
@timabbott I'd love to :)

call_on_each_event simply hands off event_types to the register method. If someone decides not to use call_on_each_event and instead opts to use register, they'll experience this same issue.

Where's the best place to fix this, at the register level, or call_on_each_event's level, or both? It seems that both are intended to be exposed to API clients.

**Comment by timabbott** [comment]
I think modfying this block in `register` to use the same pattern it uses for `narrow` would work:
```
        if narrow is None:
            narrow = []

        request = dict(
            event_types=event_types,
            narrow=narrow,
            **kwargs
        )
```
