### ISSUE TITLE
Have an easy way to find the examples from our documentation

### ISSUE THREAD

**Issue by timabbott** [zulip/python-zulip-api#92]
Because of the move to `pip install zulip` (instead of having people clone the repo or download a tarball), it's now very easy to not find the API examples that come with the package.  We should probably do some combination of:
* Adding something to our API docs that point to the example code (E.g. just a link to the directory on GitHub)
* Having a recommended command that you can run after you've done `pip install zulip` that will find the example code.  This is tricky because the files will be in some crazy path under the virtualenv's share/ directory (if you're using one) or maybe `/usr/local/share` if you installed as root or something.

(Also, I actually can't find the examples in our virtualenvs generated by `tools/provision`; are they not included in the package?)

**Comment by derAnfaenger** [comment]
For some reason, `pip install ./zulip` install the package in `Python35-32\Lib\site-packages`, but the examples and integrations in `Python35-32\share\zulip\`. Going to debug this.

**Comment by derAnfaenger** [comment]
So basically, it's because of this:
```.py
    data_files=[('share/zulip/examples',
                 ["examples/zuliprc",
                  "examples/create-user",
                  "examples/edit-message",
                  "examples/get-presence",
                  "examples/get-public-streams",
                  "examples/list-members",
                  "examples/list-subscriptions",
                  "examples/print-events",
                  "examples/print-messages",
                  "examples/recent-messages",
                  "examples/send-message",
                  "examples/subscribe",
                  "examples/unsubscribe",
                  ])] + list(recur_expand('share/zulip', 'integrations/')),
```
Is there any reason why we want to have this in a `share` directory?

**Comment by timabbott** [comment]
I think `share` is where you usually put man pages and stuff, which is why they were there.  Moving them to `lib` is probably a good idea.

**Comment by derAnfaenger** [comment]
Updated #98 for this. Right now, the script works for me with a normal install, but not with an editable install: The reason for that is the current location of the `examples` directory outside of the `zulip` package directory. Would it make sense to move `examples` into `zulip/zulip`? Also, `MANIFEST.in` seems to be outdated and includes only a subset of all scripts in `examples`.

**Comment by timabbott** [comment]
Hmm, yeah, likely we should move the examples directory into the `zulip` subdirectory to fit the preferred structure for Python packages.  Which scripts are missing from `MANIFEST.in`?  I suspect there's not a good reason for them to be.
